using Emgu.CV;
using Emgu.CV.Structure;
using Femore.Imaging.Client;
using System;
using System.Drawing;

namespace Femore.Imaging.Core
{
    /// <summary>
    /// Provides the mechanism to process an image in the prototype application.
    /// </summary>
    public static class PrototypeProcessor
    {
        /// <summary>
        /// Performs the prototype image processing against the provided image.
        /// </summary>
        /// <param name="original">The <see cref="Bitmap"/> to be processed.</param>
        /// <returns>A processed <see cref="Bitmap"/> generated by the algorithm.</returns>
        public static Bitmap Process( Bitmap original, Algorithm processingAlgorithm )
        {
            Bitmap current = original;
            foreach( var process in processingAlgorithm )
            {
                process.Process( current );
                current = process.ProcessedImage;
            }

            return current;
        }
    }
}
