using Emgu.CV;
using Emgu.CV.Structure;
using System;
using System.Drawing;

namespace Femore.Imaging.Core
{
    /// <summary>
    /// Provides the mechanism to process an image in the prototype application.
    /// </summary>
    public static class PrototypeProcessor
    {
        /// <summary>
        /// Performs the prototype image processing against the provided image.
        /// </summary>
        /// <param name="original">The <see cref="Bitmap"/> to be processed.</param>
        /// <returns>A processed <see cref="Bitmap"/> generated by the algorithm.</returns>
        public static Bitmap Process( Bitmap original )
        {
            Image<Rgb, Byte> theImg = new Image<Rgb, Byte>( original );
            theImg = theImg.SmoothGaussian( 5 );
            theImg._GammaCorrect( 1.5d );
            return theImg.Bitmap;
        }
    }
}
